# Site
repository: felix-krause/felix-krause
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Felix Krause
title: Full Stack Web Developer
email: felix.s.krause@icloud.com
website: www.github.com/felix-krause

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: felix-krause
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: felix-krause-858695193
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: felix-krause-k8n
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Profil
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Felix arbeitet seit August 2024 als Senior Software Engineer bei ELCA, mit Fokus auf <mark>.NET</mark> und <mark>Angular</mark>. Er genießt es, komplexe Software zu entwerfen und umzusetzen, um großartige Ergebnisse zu erzielen. Seine Fähigkeit, neue Technologien schnell zu erlernen, macht ihn zu einem flexiblen und vielseitigen Teammitglied. Seine analytischen Fähigkeiten sind besonders wertvoll bei der Bewältigung herausfordernder Projektthemen.

  Er ist ein erfahrener Frontend-Entwickler der es liebt grafische Benutzeroberflächen mit starkem Fokus auf <mark>Responsive Design</mark>, <mark>User Experience</mark> und <mark>Accessibility</mark> zu implementieren. Er hat das Auge und das Wissen, jeder Anwendung die zusätzliche Innovation zu verleihen, um ein echter Game-Changer zu sein. Sein Mathematik-Diplom und seine Erfahrung als ehemaliger Datenanalyst und aktueller Datenvisualisierungsexperte machen ihn zu einer wertvollen Ergänzung für jedes Projekt, das fortschrittliche Diagramme und Infografiken benötigt.

  Felix schätzt einen gut organisierten Arbeitsplatz, sowie professionelle Toolchains und Kollegen. Daher ist er aktiv an der Erstellung von Best Practices für das Web Competence Center bei ELCA beteiligt. Als erfahrener Entwickler mit Einblicken in die Leitung kleiner agiler Teams bringt er diese Werte in jedes Projekt ein, an dem er beteiligt ist.
  Als <mark>SCRUM-Enthusiast</mark> und lebenslanger Lerner freut er sich, seine Leidenschaft durch das Erlangen von Zertifikaten und der Teilnahme an Schulungen bald offiziell untermauern zu dürfen.

content:
  #   - title: Skills
  #     layout: text
  #     content: | # this will include new lines to allow paragraphs
  #       Angular, .NET, HTML5, CSS3 (SCSS/LESS), Javascript (Typescript), SVG (d3, SMIL), SQL (PostGreSQL), Docker, IAM, Azure DevOps, Github Actions

  - title: Projekte & Erfahrungen # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ELCA
        link: https://www.elca.ch
        link_text: elca.ch
        sub_title: Senior Frontend Engineer
        caption: August 2024 - Heute
        description: | # this will include new lines to allow paragraphs
          Research & Development, Trainings und Reviews in verschiedenen internen und Kundenprojekten. 

          Dabei wird von Scaffolding & Projektsetup über Cloud-Engineering bis zum Feinschliff des fertigen Releases seine Expertise benötigt.
      - layout: left
        title: EBG
        link: https://www.ebg.admin.ch/
        link_text: ebg.admin.ch
        sub_title: Lead Dev, Senior Frontend Engineer
        caption: November 2022 - Juni 2024
        quote: >
          EPIC zertifizierte Software (Equal Pay International Coalition, led by the ILO, UN Women, and the OECD)
        description: | # this will include new lines to allow paragraphs
          Prototyping, Entwicklung und Einführung einer kostenfreien cloudbasierten Web App zur Erstellung eines Lohnsystems für Klein- und Mittelständische Unternehmen anhand statistischer Analyse aktueller Lohndaten. In einem einfachen Prozess erfassen Benutzer die erforderlichen Daten und werden mithilfe von interaktiven Diagrammen zum Ergebnis geführt. 

          **Webprojekt-Link:**   https://www.logib.admin.ch
      - layout: left
        title: Bundeskanzlei
        link: https://www.bk.admin.ch/
        link_text: bk.admin.ch
        sub_title: Fullstack Developer
        caption: März 2020 - August 2022
        description: | # this will include new lines to allow paragraphs
          Als Teil eines festen SCRUM Teams wurde eine cloudbasierte Neuentwicklung eines Sitzungsverwaltungstool für den Bundesrat, in dem Sitzungen geplant, vorbereitet und protokolliert werden können, umgesetzt. Wegen der beschleunigten Digitalisierung durch Covid-19 wurden zahlreiche weitere Apps umgesetzt. 

          **Webprojekt-Link:**  https://www.staatskalender.admin.ch/home
      - layout: left
        title: SwissMedic
        link: https://www.swissmedic.ch/
        link_text: swissmedic.ch
        sub_title: IT Consultant
        caption: Februar 20219 - Januar 2021
        description: | # this will include new lines to allow paragraphs
          System zur Erstellung und Freigabe von Beipackzetteln für Arzneimittel. Die Verarbeitung, Publizierung und Verifikation wird auf einem intern gehostetem Serversystem welches ein einfaches Access Management mit sich bringt, duchgeführt.
      - layout: left
        title: BKW
        link: https://www.bkw.ch/
        link_text: bkw.ch
        sub_title: IT Consultant
        caption: August 20217 - Januar 2019
        description: | # this will include new lines to allow paragraphs
          Auswertungstool für Daten aus diversen Umsystemen. Die gesammelten Daten wurden im UI mit leicht verständlichen Grafen dargestellt und konnten vom Benutzer mit eigenen Daten und Kommentaren ergänzt und verbessert werden, um offizielle monatliche Datenauszüge zu generieren.
      - layout: left
        title: H-O-T
        link: https://www.hot-online.de
        link_text: hot-online.de
        sub_title: IT Consultant
        caption: Februar 2016 - März 2017
        description: | # this will include new lines to allow paragraphs
          Vollintegrierte Industrie 4.0 Softwarelösung. Durch die Benutzung von Robotorprogrammiersprachen, QR Codes, Kamerasystem und Scannern konnten Teile und Produkte zu jedem Zeitpunkt automatisiert verfolgt werden.
      - layout: left
        title: Frühere Anstellungen
        sub_title: IT Consultant
        caption: Mai 2011 - August 2015
        description: | # this will include new lines to allow paragraphs
          Diverse IT-Lösungen für verschiedene Industrie und Pharmaunternehmen, darunter Microsoft .NET Product Trainings, Inhouse Product Trainings. Process Automation, Collaboration Solutions und Management Assistenz.

  # - title: Privat Programmiert # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Ausbildung # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: OTH Regensburg
        caption: 2006 - 2011
        sub_title: Dipl. Math.
        quote: >
          Die OTH Regensburg ist eine der forschungsstärksten Hochschulen für angewandte Wissenschaften in Bayern
        description: | # this will include new lines to allow paragraphs
          Während seiner Zeit in Regensburg lernte Felix neben der angewandten Mathematik viele Skills die er noch heute im Beruflichen Alltag benötigt, wie Teamwork und Zeitmanagement.

          Als Mathematik-Tutor für Ingenieurswissenschaften konnte er früh lernen wie erfüllend es sein kann, Wissen zu teilen.

  - title: Persönliche Vorlieben
    layout: text
    content: | # this will include new lines to allow paragraphs
      Felix geht seinen Interesse im Software Engineering auch nach seiner Arbeit nach, wie zahlreiche private Projekte zeigen.
      Falls er dennoch etwas Zeit findet, geht er gerne fernab von jeder Autobahn oder Zuglinie wandern, spielt gerne uralte oder brandneue Brettspiele und macht [Musik](https://youtu.be/4hN3P9NMQLs).
      Felix trink lieber Tee als Kaffee, trinkt sein Wasser lieber mit Sprudel als ohne und liebt sowohl Hunde als auch Katzen.

# Footer
footer_show_references: true
references_title: Referenzen auf Nachfrage

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
